# Generated by Django 5.2.5 on 2025-08-13 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="images",
            new_name="images_url",
        ),
    ]
