# Generated by Django 5.2.4 on 2025-08-22 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_images_property_images_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images_url',
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('Indore', 'Indore'), ('Ujjain', 'Ujjain'), ('Bhopal', 'Bhopal'), ('Gwalior', 'Gwalior')], max_length=255),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/properties')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
        ),
    ]
