# Generated by Django 5.2.4 on 2025-10-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_owner'),
        ('property', '0006_alter_booking_name_alter_booking_phone'),
    ]

    operations = [
    ]
